---
remote_user: "{{ remote_user }}"
email_address: 'kisssulran@i-screammedia.com'
app_dir: nginx
nginx_base_directory: "{{ nginx_base_directory }}"
nginx_reverse_proxy_config_directory: "{{ nginx_base_directory }}/conf.d"
nginx_container_name: 'nginx'
nginx_docker_tag: 'latest'
nginx_static_html_directory: 'defaults'
nginx_ssl_cert_name: "cert.pem"
nginx_ssl_key_name: "key.pem"
nginx_ssl_certificate_path: "{{ nginx_base_directory }}/conf.d/cert.pem"
nginx_ssl_certificate_key_path: "{{ nginx_base_directory }}/conf.d/key.pem"
nginx_sites_enabled_path: "{{ nginx_base_directory }}/sites-enabled"
nginx_log_dir_path: "/var/log/nginx"
nginx_reverse_proxy_proxies: []

docker_network_name: "{{ docker_network_name }}"

nginx_exposed_ports:
  - '80'
  - '443'

nginx_published_ports:
  - '80:80'
  - '443:443'

nginx_exposed_volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/letsencrypt:/etc/letsencrypt
  - /var/www/letsencrypt:/var/www/letsencrypt
  - /var/log/nginx:/var/log/nginx
  - "{{ nginx_base_directory }}/nginx.conf:/etc/nginx/nginx.conf:ro"
  - "{{ nginx_base_directory }}/defaults:/usr/share/nginx/html:ro"
  - "{{ nginx_reverse_proxy_config_directory }}:/etc/nginx/conf.d:rw"
  - "{{ nginx_sites_enabled_path }}:/etc/nginx/sites-enabled:ro"

nginx_conf: |
  user  nginx;
  worker_processes auto;

  pid /var/run/nginx.pid;

  events {
      worker_connections  65535;
      multi_accept on;
      use epoll;
  }

  http {
      server_tokens off;
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log off;
      log_not_found off;
      error_log  /var/log/nginx/error.log crit;

      sendfile on;
      tcp_nodelay off;
      tcp_nopush off;
      keepalive_timeout  65;

      #gzip  on;

      include /etc/nginx/conf.d/*.conf;
      include /etc/nginx/conf.d/general-security-headers.conf;
      include /etc/nginx/sites-enabled/*;
  }
